name: Build, Optimize & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Inject GA + GSC
      - name: Inject GA and GSC
        run: |
          GA_ID="G-S8DEQ62FVN"   # <-- your GA4 Measurement ID
          GSC_CODE="phaJ6eaZUl6EU_Wkv3H90PM91RrLOxZlfXXH078L49o"   # <-- your GSC code

          GA_SCRIPT='<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id='"$GA_ID"'></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag("js", new Date());
  gtag("config", "'"$GA_ID"'");
</script>'

          GSC_TAG='<meta name="google-site-verification" content="'"$GSC_CODE"'" />'

          find . -type f -name "*.html" | while read file; do
            # Inject GA only if missing
            if ! grep -q "$GA_ID" "$file"; then
              echo "Injecting GA into $file"
              sed -i "/<\/head>/i $GA_SCRIPT" "$file"
            else
              echo "Skipping GA (already present) in $file"
            fi

            # Inject GSC tag only if missing
            if ! grep -q "$GSC_CODE" "$file"; then
              echo "Injecting GSC into $file"
              sed -i "/<\/head>/i $GSC_TAG" "$file"
            else
              echo "Skipping GSC (already present) in $file"
            fi
          done

      # 3. Generate sitemap.xml
      - name: Generate sitemap.xml
        run: |
          npx sitemap-generator-cli https://www.romanulislam.com \
            --strip-querystring true \
            --max-depth 5 \
            --output ./sitemap.xml

      # 4. Validate sitemap XML syntax
      - name: Validate sitemap
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          xmllint --noout sitemap.xml

      # 5. Deploy to Cloudflare Pages
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: mysite   # <-- must match Cloudflare Pages project name
          directory: .
